<html>
<head>
<script src="../../../http/tests/inspector/inspector-test.js"></script>
<script src="../../../http/tests/inspector/debugger-test.js"></script>
<script>

function throwAnException()
{
    return unknown_var;
}

function handleClick()
{
    throwAnException();
}

var test = function()
{
    InspectorTest.startDebuggerTest(step1);

    function step1()
    {
        InspectorTest.DebuggerAgent.setPauseOnExceptions(WebInspector.DebuggerModel.PauseOnExceptionsState.PauseOnUncaughtExceptions);
        InspectorTest.showScriptSource("debugger-pause-on-exception.html", step2);
    }

    function step2()
    {
        InspectorTest.addResult("Script source was shown.");
        InspectorTest.evaluateInPage("setTimeout(handleClick, 0)");
        InspectorTest.waitUntilPausedAndDumpStackAndResume(step3);
    }

    function step3()
    {
        InspectorTest.DebuggerAgent.setPauseOnExceptions(WebInspector.DebuggerModel.PauseOnExceptionsState.DontPauseOnExceptions);
        InspectorTest.completeDebuggerTest();
    }
}

</script>
</head>

<body onload="runTest()">
<p>
Tests that pause on exception works.
</p>

</body>
</html>
