This is a testharness.js-based test.
FAIL TrackEvent created with createEvent assert_throws: function "function () {
        var ev = document.createEvent('Trac..." did not throw
Harness: the test ran to completion.

