This is a testharness.js-based test.
PASS new DOMException() 
PASS new DOMException(): own-ness 
PASS new DOMException(null) 
PASS new DOMException(undefined) 
PASS new DOMException(undefined): own-ness 
PASS new DOMException("foo") 
FAIL new DOMException("foo"): own-ness assert_true: The message property should be own expected true got false
PASS new DOMException("bar", undefined) 
PASS new DOMException("bar", "NotSupportedError") 
FAIL new DOMException("bar", "NotSupportedError"): own-ness assert_true: The name property should be own expected true got false
PASS new DOMException("bar", "foo") 
PASS new DOMexception("msg", "IndexSizeError") 
PASS new DOMexception("msg", "HierarchyRequestError") 
PASS new DOMexception("msg", "WrongDocumentError") 
PASS new DOMexception("msg", "InvalidCharacterError") 
PASS new DOMexception("msg", "NoModificationAllowedError") 
PASS new DOMexception("msg", "NotFoundError") 
PASS new DOMexception("msg", "NotSupportedError") 
PASS new DOMexception("msg", "InUseAttributeError") 
PASS new DOMexception("msg", "InvalidStateError") 
PASS new DOMexception("msg", "SyntaxError") 
PASS new DOMexception("msg", "InvalidModificationError") 
PASS new DOMexception("msg", "NamespaceError") 
PASS new DOMexception("msg", "InvalidAccessError") 
PASS new DOMexception("msg", "SecurityError") 
PASS new DOMexception("msg", "NetworkError") 
PASS new DOMexception("msg", "AbortError") 
PASS new DOMexception("msg", "URLMismatchError") 
PASS new DOMexception("msg", "QuotaExceededError") 
PASS new DOMexception("msg", "TimeoutError") 
PASS new DOMexception("msg", "InvalidNodeTypeError") 
PASS new DOMexception("msg", "DataCloneError") 
PASS new DOMException("bar", "UnknownError") 
Harness: the test ran to completion.

